# Requires Ansible 2.5+
# pip install --upgrade ansible
# run with
# ansible-playbook install_pulp_3.yaml  -i hostname, -v

# If your host is a Fedora 26+ server go to:
# https://hostname:9090/system/logs#/?prio=* to follow the logs

# Ensure you can access the hostname via ssh without password
# ssh-copy-id -i ~/.ssh/id_rsa root@hostname
# or use 
# ansible-playbook install_pulp_3.yaml -i root@hostname, --ask-pass -v

- name: Install Pulp 3
  hosts: all
  gather_facts: false
  become: true
  user: root

  vars:
    
    ansible_connection: ssh 
    ansible_ssh_user: root
    ansible_python_interpreter: /usr/bin/python3

    venv: "/home/vagrant/.virtualenvs/pulp/"
    pythonbin: "/home/vagrant/.virtualenvs/pulp/bin/python"
    pulpmanager: "/home/vagrant/.virtualenvs/pulp/bin/pulp-manager"
    address: "0.0.0.0:8000"

  tasks:

    - name: Install Packages
      loop:
        - ansible
        - python3
        - git
        - screen
      dnf:
        name: "{{item}}"
        state: latest

    - name: Disable SELINUX
      selinux:
        state: disabled

    - name: Stop Firewalld
      systemd:
        name: firewalld
        state: stopped
        masked: yes

    - name: Clone the pulp devel repo
      git:
        repo: https://github.com/pulp/devel.git
        dest: "~/devel"

    # - name: Write {{inventory_hostname}} to the hosts file
    #   lineinfile:
    #     path: "~/devel/ansible/hosts"
    #     create: yes
    #     line: "{{inventory_hostname}}"

    # cd ~/devel/ansible && 
    - name: Run Ansible Playbook to install pulp from source in {{inventory_hostname}}
      shell: ansible-playbook pulp-from-source.yml -i {{inventory_hostname}}, --connection local
      args:
        chdir: "~/devel/ansible"
      ignore_errors: yes
  
    - name: Install Pulp-File plugin
      become: yes
      become_user: vagrant
      pip:
        name: git+https://github.com/pulp/pulp_file.git#egg=pulp-file
        virtualenv: "{{ venv }}"

    - name: Make pulp_file migrations
      become: yes
      become_user: vagrant
      shell: "{{pulpmanager}} makemigrations pulp_file"

    - name: Run pulp_file migrations
      become: yes
      become_user: vagrant
      shell: "{{pulpmanager}} migrate pulp_file"

    - name: Start services
      shell: systemctl restart pulp_{resource_manager,worker@{1,2}}

    - name: Start the Django Server in a screen (screen -r pulp3) to attach
      become: yes
      become_user: vagrant
      shell: screen -dmS pulp3 sh -c '{{ pulpmanager }} runserver {{ address }};exec bash'
