# Requires Ansible 2.5+
# pip install --upgrade ansible
# run with
# ansible-playbook reset_pulp.yaml  -i host.where.pulp.is.installed.com, -v

- name: Reset Pulp 2
  hosts: all
  gather_facts: false
  become: true
  user: root

  vars:
    ansible_connection: ssh 
    ansible_ssh_user: root
    services:
      - httpd
      - pulp_workers
      - pulp_celerybeat
      - pulp_resource_manager
      - qpidd

  tasks:

    - name: Stop all services
      loop: "{{ services }}"
      systemd:
        name: "{{ item }}"
        state: stopped
      
    - name: Drop Mongo Database
      shell: mongo pulp_database --eval 'db.dropDatabase()'

    - name: Run Pulp Manage DB
      shell: runuser --shell /bin/sh apache --command pulp-manage-db

    - name: Remove Pulp Contents
      loop:
        - /var/lib/pulp/content
        - /var/lib/pulp/published
      file: path={{item}} state=absent

    - name: Start all services
      loop: "{{ services }}"
      systemd:
        name: "{{ item }}"
        state: started

    - name: Run Pulp status  
      shell: pulp-admin -v status
      register: out

    - debug: var=out.stdout_lines
