# ansible-playbook -vvv -i <hostname>, -u root source-install.yml
---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    pulp_source_dir: 
        - "https://github.com/pulp/pulpcore/tarball/master"
        - psycopg2-binary
    pulp_plugin_source_dir: "https://github.com/pulp/pulpcore-plugin/tarball/master"
    pulp_secret_key: "unsafe_default"
    pulp_default_admin_password: admin
    pulp_pip_editable: no
    pulp_install_plugins:
      pulp-file:
        app_label: "file"
        source_dir: "https://github.com/pulp/pulp_file/tarball/master"
  roles:
    - pulp-database
    - pulp-workers
    - pulp-resource-manager
    - pulp-webserver
    - pulp-content
  post_tasks:
    - name: Disable Firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: False
